version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Specify the Dockerfile to use
    ports:
      - "8000:9000" # Map host port 8000 to container port 9000
    volumes:
      - .:/var/www/html
    env_file:
      - .env # Use the separate .env.docker file for environment variables
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: 6valy_db
      MYSQL_USER: admin  # Change this to your desired database username
      MYSQL_PASSWORD: password  # Change this to your desired database password
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:

